### ISSUE TITLE
Mini Project !!

### ISSUE THREAD

**Issue by vishwasT007** [Bharathgopal/M1_March_2022#139] opened 2022-03-17 11:58 UTC
What type of mini projects can we make....can we take reference from someone's project for learning purpose?

**Comment by Bharathgopal** [comment] 2022-03-18 07:00
Duplicate of [Issue 140](https://github.com/Bharathgopal/M1_March_2022/issues/140)

**Closed by Bharathgopal** 2022-03-18 07:00 UTC
Labels: duplicate
