### ISSUE TITLE
not able to download linux certificate

### ISSUE THREAD

**Issue by mpulkit05** [Bharathgopal/M1_March_2022#5] opened 2022-03-14 10:51 UTC
what to do?
where to get help?

**Comment by junaidferoz** [comment] 2022-03-14 10:52
hey!! clock on cisco netacad and login and click on get certificate

**Comment by batcha333** [comment] 2022-03-14 11:37
once after you complete your exam just close the current page and open your NDG unhatched linux link  again, u can able to download your certificate via a star icon!!!

**Comment by ITSMEUNICK-21** [comment] 2022-03-15 04:39
Please have a look here : 
https://github.com/Bharathgopal/M1_March_2022/issues/23#issuecomment-1066687408

**Comment by Bharathgopal** [comment] 2022-03-18 07:20
Duplicate of [Issue 23](https://github.com/Bharathgopal/M1_March_2022/issues/23)

**Closed by Bharathgopal** 2022-03-18 07:20 UTC
