### ISSUE TITLE
Where to send repository link of certificates.

### ISSUE THREAD

**Issue by Nikhilkumarray** [Bharathgopal/M1_March_2022#115] opened 2022-03-14 11:58 UTC

**Comment by junaidferoz** [comment] 2022-03-14 12:02
Create a repository on your account.
there click on create file and new file.
then you will select the certificate and click OK. that should help

**Comment by GuturiDhanushkumar** [comment] 2022-03-14 12:05
I think they will tell later that were we have to submit that repository link

**Comment by Bharathgopal** [comment] 2022-03-18 06:53
A submission form will be released on the day of Project submissions.

**Comment by Bharathgopal** [comment] 2022-03-18 07:09
Duplicate of [Issue 140](https://github.com/Bharathgopal/M1_March_2022/issues/140#issuecomment-1072083117)

**Closed by Bharathgopal** 2022-03-18 07:09 UTC
Labels: duplicate
