### ISSUE TITLE
not able to install GCC in windows

### ISSUE THREAD

**Issue by Harshadhhh** [Bharathgopal/M1_March_2022#2] opened 2022-03-14 10:50 UTC

**Comment by akkivanguu** [comment] 2022-03-14 11:43
u can use gcc. file from official website and just make environmental variable path setup.. and u ready to use gcc

**Comment by Bharathgopal** [comment] 2022-03-18 07:17
Duplicate of [Issue 1](https://github.com/Bharathgopal/M1_March_2022/issues/1)

**Closed by Bharathgopal** 2022-03-18 07:17 UTC
Labels: duplicate
