### ISSUE TITLE
Add certificates

### ISSUE THREAD

**Issue by junaidferoz** [Bharathgopal/M1_March_2022#7] opened 2022-03-14 10:51 UTC
* do we have to add certificates here or we create our own repo and send it there so that you could see it? i would like to clear this doubt

**Comment by Bharathgopal** [comment] 2022-03-18 07:21
Duplicate of [Issue 140](https://github.com/Bharathgopal/M1_March_2022/issues/140)

**Closed by Bharathgopal** 2022-03-18 07:21 UTC
Labels: duplicate
